postgres:
  host: localhost
  port: 5432
  user: trading_bot
  password: trading_bot_pwd
  database: trading_bot_db
  minsize: 1
  maxsze: 5
alpaca:
  API_KEY: PKEXG1SB9ZYHPV0B87U9
  SECRET_KEY: iapgCvvRjKdoAVMVQa78hZ2KmgkxTxyIQtK8UepL