postgres:
  host: localhost
  port: 5432
  user: trading_bot
  password: trading_bot_pwd
  database: trading_bot_db
  minsize: 1
  maxsze: 5
alpaca:
  API_KEY: PKKVITUK07ID86C1SNDL 
  SECRET_KEY: wTejgyOzMZgTrC7efjQ5JnLDJHXOuOqBSl3o2Og7