postgres:
  host: localhost
  port: 5432
  user: postgres
  password: trading_bot_pwd
  database: postgres
  minsize: 1
  maxsize: 5
alpaca:
  API_KEY: PKKVITUK07ID86C1SNDL 
  SECRET_KEY: wTejgyOzMZgTrC7efjQ5JnLDJHXOuOqBSl3o2Og7