postgres:
  host: localhost
  port: 5432
  user: trading_bot
  password: trading_bot_pwd
  database: trading_bot_db
  minsize: 1
  maxsze: 5
alpaca:
  API_KEY: PKDUAO4VPC0R5H3UKPFG
  SECRET_KEY: 3QGQ3BDDQid0GEZcZd6PkAhdIbKdmzE7WmQO1TYz